package postgres

import (
	schemax "github.com/arcgolabs/dbx/schema"
	"reflect"
	"slices"
	"strings"

	"github.com/arcgolabs/collectionx"
	"github.com/samber/lo"
)

var postgresNormalizedTypes = map[string]string{
	"int2":                        "smallint",
	"smallint":                    "smallint",
	"int4":                        "integer",
	"integer":                     "integer",
	"serial":                      "integer",
	"serial4":                     "integer",
	"int8":                        "bigint",
	"bigint":                      "bigint",
	"bigserial":                   "bigint",
	"serial8":                     "bigint",
	"float4":                      "real",
	"real":                        "real",
	"float8":                      "double",
	"double precision":            "double",
	"numeric":                     "double",
	"decimal":                     "double",
	"bool":                        "boolean",
	"boolean":                     "boolean",
	"varchar":                     "text",
	"bpchar":                      "text",
	"text":                        "text",
	"citext":                      "text",
	"bytea":                       "blob",
	"timestamp":                   "timestamp",
	"timestamptz":                 "timestamp",
	"timestamp with time zone":    "timestamp",
	"timestamp without time zone": "timestamp",
}

var (
	postgresIntKinds         = []reflect.Kind{reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32}
	postgresUnsignedIntKinds = []reflect.Kind{reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32}
)

func (d Dialect) columnDDL(column schemax.ColumnMeta, inlinePrimaryKey, includeReference bool) string {
	parts := []string{
		d.QuoteIdent(column.Name),
		postgresColumnTypeDDL(column),
	}

	parts = append(parts, postgresColumnConstraintParts(column, inlinePrimaryKey)...)
	if includeReference {
		parts = append(parts, d.postgresReferenceParts(column)...)
	}

	return strings.Join(parts, " ")
}

func postgresColumnTypeDDL(column schemax.ColumnMeta) string {
	typeName := resolvedPostgresType(column)
	if column.AutoIncrement {
		return typeName + " GENERATED BY DEFAULT AS IDENTITY"
	}
	return typeName
}

func postgresColumnConstraintParts(column schemax.ColumnMeta, inlinePrimaryKey bool) []string {
	parts := make([]string, 0, 3)
	if inlinePrimaryKey {
		parts = append(parts, "PRIMARY KEY")
	}
	if !column.Nullable && !inlinePrimaryKey {
		parts = append(parts, "NOT NULL")
	}
	if column.DefaultValue != "" && !column.AutoIncrement {
		parts = append(parts, "DEFAULT "+column.DefaultValue)
	}
	return parts
}

func (d Dialect) postgresReferenceParts(column schemax.ColumnMeta) []string {
	if column.References == nil {
		return nil
	}

	parts := []string{
		"REFERENCES " + d.QuoteIdent(column.References.TargetTable) + " (" + d.QuoteIdent(column.References.TargetColumn) + ")",
	}
	if column.References.OnDelete != "" {
		parts = append(parts, "ON DELETE "+string(column.References.OnDelete))
	}
	if column.References.OnUpdate != "" {
		parts = append(parts, "ON UPDATE "+string(column.References.OnUpdate))
	}
	return parts
}

func resolvedPostgresType(column schemax.ColumnMeta) string {
	if column.SQLType != "" {
		return column.SQLType
	}
	return postgresType(column)
}

func (d Dialect) primaryKeyDDL(primaryKey schemax.PrimaryKeyMeta) string {
	return "CONSTRAINT " + d.QuoteIdent(primaryKey.Name) + " PRIMARY KEY (" + d.joinQuotedIdentifiers(primaryKey.Columns) + ")"
}

func (d Dialect) foreignKeyDDL(foreignKey schemax.ForeignKeyMeta) string {
	parts := collectionx.NewList[string]()
	parts.Add("CONSTRAINT " + d.QuoteIdent(foreignKey.Name))
	parts.Add("FOREIGN KEY (" + d.joinQuotedIdentifiers(foreignKey.Columns) + ")")
	parts.Add("REFERENCES " + d.QuoteIdent(foreignKey.TargetTable) + " (" + d.joinQuotedIdentifiers(foreignKey.TargetColumns) + ")")
	if foreignKey.OnDelete != "" {
		parts.Add("ON DELETE " + string(foreignKey.OnDelete))
	}
	if foreignKey.OnUpdate != "" {
		parts.Add("ON UPDATE " + string(foreignKey.OnUpdate))
	}
	return joinPostgresStrings(parts, " ")
}

func (d Dialect) checkDDL(check schemax.CheckMeta) string {
	return "CONSTRAINT " + d.QuoteIdent(check.Name) + " CHECK (" + check.Expression + ")"
}

func postgresType(column schemax.ColumnMeta) string {
	if column.SQLType != "" {
		return column.SQLType
	}
	if column.GoType == nil {
		return "TEXT"
	}

	typ := dereferencePostgresType(column.GoType)
	if isPostgresTimeType(typ) {
		return "TIMESTAMPTZ"
	}
	if isPostgresBlobType(typ) {
		return "BYTEA"
	}
	if mapped, ok := postgresKindType(typ.Kind()); ok {
		return mapped
	}
	return fallbackPostgresType(typ)
}

func postgresKindType(kind reflect.Kind) (string, bool) {
	switch {
	case kind == reflect.Bool:
		return "BOOLEAN", true
	case slices.Contains(postgresIntKinds, kind):
		return "INTEGER", true
	case kind == reflect.Int64:
		return "BIGINT", true
	case slices.Contains(postgresUnsignedIntKinds, kind):
		return "INTEGER", true
	case kind == reflect.Uint64:
		return "BIGINT", true
	case kind == reflect.Float32:
		return "REAL", true
	case kind == reflect.Float64:
		return "DOUBLE PRECISION", true
	case kind == reflect.String:
		return "TEXT", true
	default:
		return "", false
	}
}

func dereferencePostgresType(typ reflect.Type) reflect.Type {
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	return typ
}

func isPostgresTimeType(typ reflect.Type) bool {
	return typ.PkgPath() == "time" && typ.Name() == "Time"
}

func isPostgresBlobType(typ reflect.Type) bool {
	return typ.Kind() == reflect.Slice && typ.Elem().Kind() == reflect.Uint8
}

func fallbackPostgresType(typ reflect.Type) string {
	if name := typ.Name(); name != "" {
		return strings.ToUpper(name)
	}
	return "TEXT"
}

func parseIndexColumns(definition string) []string {
	start := strings.Index(definition, "(")
	end := strings.LastIndex(definition, ")")
	if start < 0 || end <= start {
		return nil
	}

	parts := strings.Split(definition[start+1:end], ",")
	return lo.Compact(lo.Map(parts, func(part string, _ int) string {
		return strings.TrimSpace(strings.Trim(part, `"`))
	}))
}

func singlePrimaryKeyColumn(primaryKey *schemax.PrimaryKeyMeta) string {
	if primaryKey == nil || primaryKey.Columns.Len() != 1 {
		return ""
	}
	column, _ := primaryKey.Columns.GetFirst()
	return column
}

func (d Dialect) joinQuotedIdentifiers(items collectionx.List[string]) string {
	if items.Len() == 0 {
		return ""
	}
	quoted := items.Values()
	for index, item := range quoted {
		quoted[index] = d.QuoteIdent(item)
	}
	return strings.Join(quoted, ", ")
}

func joinPostgresStrings(items collectionx.List[string], sep string) string {
	if items.Len() == 0 {
		return ""
	}
	return strings.Join(items.Values(), sep)
}

func referentialAction(value string) schemax.ReferentialAction {
	switch strings.ToUpper(strings.TrimSpace(value)) {
	case string(schemax.ReferentialCascade):
		return schemax.ReferentialCascade
	case string(schemax.ReferentialRestrict):
		return schemax.ReferentialRestrict
	case string(schemax.ReferentialSetNull):
		return schemax.ReferentialSetNull
	case string(schemax.ReferentialSetDefault):
		return schemax.ReferentialSetDefault
	case string(schemax.ReferentialNoAction):
		return schemax.ReferentialNoAction
	default:
		return ""
	}
}
